name: deploy

on:
  # 每当 push 到 main 分支时触发部署
  # Deployment is triggered whenever a push is made to the main branch.
  push:
    branches: [main]
  # 手动触发部署
  # Manually trigger deployment
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
          # "Last updated time" and other git log-related information require fetching all commit records.
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          # 选择要使用的 node 版本
          node-version: 20

      # 安装依赖
      # Install dependencies
      - name: Install Dependencies
        run: npm ci



      # 运行构建脚本
      # Run the build script
      - name: Build VuePress site
        run: npm run docs:build


      # 查看 workflow 的文档来获取更多信息
      # @see https://github.com/crazy-max/ghaction-github-pages
      - name: Deploy to GitHub Pages
        run: |
          git remote add deploy-repo https://github.com/qinyuanchun03/vueblog.io.git
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git checkout -b blogs || true
          rm -rf *
          cp -r docs/.vuepress/dist/* .
          git add .
          git commit -m "Deploy to blogs branch"
